basePath: /api/v1/
consumes:
- application/json
definitions:
  authors_pb.AuthorModel:
    properties:
      about:
        type: string
      id:
        type: string
      name:
        type: string
      profilepicture:
        type: string
      rating:
        type: number
      translitname:
        type: string
    type: object
  authors_pb.GetAuthorsResponse:
    properties:
      authors:
        items:
          $ref: '#/definitions/authors_pb.AuthorModel'
        type: array
    type: object
  genres_pb.CategoryModel:
    properties:
      genres:
        items:
          $ref: '#/definitions/genres_pb.GenreModel'
        type: array
      id:
        type: string
      name:
        type: string
      translitName:
        type: string
    type: object
  genres_pb.GenreModel:
    properties:
      bookCount:
        type: integer
      id:
        type: string
      name:
        type: string
      translitName:
        type: string
    type: object
  middleware.CustomError:
    description: General error object. This structure always returns when error occurred
    properties:
      code:
        description: Internal gRPC error code (e.g. 3)
        example: 3
        type: integer
      details:
        description: Error details. Check 'ErrorDetail' structure for more information
        items: {}
        type: array
      message:
        description: Error message. Can be shown to users
        example: Bad token provided
        type: string
      type:
        description: Error code in string (e.g. InvalidArgument)
        example: InvalidArgument
        type: string
    type: object
  shared_pb.ErrorDetail:
    description: Error detail contains information about error
    properties:
      actualvalue:
        description: 'Actual value of field that causes the error. Note: ''password''
          field will be hidden'
        example: token
        type: string
      description:
        description: Error description. Only development purposes, do not show users
        example: Field must be a jwt token
        type: string
      field:
        description: Field that error occured on
        example: Token
        type: string
      struct:
        description: Structure that contains field
        example: users_pb.TokenRequest
        type: string
      tag:
        description: Failed validation tag
        example: jwt
        type: string
    type: object
  user.UserAuthenticate.UserResponse:
    properties:
      login:
        example: admin
        type: string
      roles:
        example:
        - user
        items:
          type: string
        type: array
    type: object
  user.UserLogin.UserResponse:
    properties:
      login:
        example: admin
        type: string
      roles:
        example:
        - user
        items:
          type: string
        type: array
    type: object
  user.UserRegister.UserResponse:
    properties:
      login:
        example: admin
        type: string
      roles:
        example:
        - user
        items:
          type: string
        type: array
    type: object
  users_pb.LoginRequest:
    properties:
      login:
        description: Can be presented as login or email
        example: admin
        type: string
      password:
        example: admin
        type: string
    required:
    - login
    - password
    type: object
  users_pb.RegistrationRequest:
    properties:
      email:
        type: string
      login:
        maxLength: 16
        minLength: 4
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
      password_repeat:
        type: string
    required:
    - email
    - login
    - password
    - password_repeat
    type: object
  users_pb.UserModel:
    properties:
      email:
        type: string
      id:
        type: string
      login:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
host: localhost:9000
info:
  contact: {}
  title: API
  version: "1.0"
paths:
  /authors:
    get:
      description: |-
        there can be multiple search parameters, id or translit, or both
        example: ?id=1&id=2&translit=author-21&id=3&translit=author-756342
      parameters:
      - description: Author Id, must be a primitive id hex
        in: query
        name: id
        type: string
      - description: Translit author name
        in: query
        name: translit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Authors
          schema:
            items:
              $ref: '#/definitions/authors_pb.GetAuthorsResponse'
            type: array
        "400":
          description: Field was not in a correct format
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "404":
          description: Authors not found
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "500":
          description: Some internal error
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "503":
          description: Service does not responding (maybe crush)
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
      summary: Find authors
      tags:
      - authors
  /authors/suggest:
    get:
      description: find authors by provided phares, keys or names
      parameters:
      - description: Author Id, must be a primitive id hex
        in: query
        name: query
        required: true
        type: string
      - description: limit authors to display. default = 5 if not specified, min =
          1, max = 10
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Authors
          schema:
            items:
              $ref: '#/definitions/authors_pb.GetAuthorsResponse'
            type: array
        "400":
          description: Query was empty
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "404":
          description: Authors not found
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "500":
          description: Some internal error
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "503":
          description: Service does not responding (maybe crush)
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
      summary: Find authors by keywords
      tags:
      - authors
  /genres/all:
    get:
      description: Fetches all categories (with genres included)
      produces:
      - application/json
      responses:
        "200":
          description: Genres fetched successfully
          schema:
            items:
              $ref: '#/definitions/genres_pb.CategoryModel'
            type: array
        "404":
          description: There's no genres in database
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "500":
          description: Internal error occurred
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "503":
          description: Service does not responding (maybe crush)
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
      summary: Get all genres
      tags:
      - genres
  /users:
    get:
      description: |-
        params goes in specific order: id -> login -> email
        first found user will be returned. If no user found, there'll be an error with details
      parameters:
      - description: User Id
        in: query
        name: id
        type: string
      - description: User login
        in: query
        name: login
        type: string
      - description: User email
        format: email
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User DTO model
          schema:
            $ref: '#/definitions/users_pb.UserModel'
        "400":
          description: Request's field was not in a correct format
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "404":
          description: User not found
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "503":
          description: Service does not responding (maybe crush)
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
      summary: Find user by credentials
      tags:
      - users
  /users/auth:
    get:
      description: check if current user has legit token
      produces:
      - application/json
      responses:
        "200":
          description: User successfully authorized
          schema:
            $ref: '#/definitions/user.UserAuthenticate.UserResponse'
        "401":
          description: User does not authorized
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "404":
          description: User does not exists in database
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "503":
          description: Service does not responding (maybe crush)
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
      security:
      - ApiKeyAuth: []
      summary: Authenticates user
      tags:
      - users
  /users/login:
    post:
      description: log in user with provided login and password
      parameters:
      - description: Login field can be presented as login and email as well
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users_pb.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully authorized
          schema:
            $ref: '#/definitions/user.UserLogin.UserResponse'
        "400":
          description: Invalid request data
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "503":
          description: Service does not responding (maybe crush)
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
      summary: Authorizes user
      tags:
      - users
  /users/signin:
    post:
      description: creates new user and authorizes it
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users_pb.RegistrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered and authorized
          schema:
            $ref: '#/definitions/user.UserRegister.UserResponse'
        "400":
          description: Invalid request data
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "500":
          description: Some internal error occurred
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
        "503":
          description: Service does not responding (maybe crush)
          schema:
            allOf:
            - $ref: '#/definitions/middleware.CustomError'
            - properties:
                details:
                  items:
                    $ref: '#/definitions/shared_pb.ErrorDetail'
                  type: array
              type: object
      summary: Registration
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: Cookie
    name: Authorization
    type: apiKey
swagger: "2.0"
