basePath: /api/v1/
consumes:
- application/json
definitions:
  handlers.UserAuthenticate.UserResponse:
    properties:
      login:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
  handlers.UserLogin.UserResponse:
    properties:
      login:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
  middleware.CustomError:
    properties:
      code:
        type: integer
      details:
        items: {}
        type: array
      message:
        type: string
      type:
        type: string
    type: object
  users_pb.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  title: API
  version: "1.0"
paths:
  /users/auth:
    get:
      description: check if current user has legit token
      produces:
      - application/json
      responses:
        "200":
          description: User successfully authorized
          schema:
            $ref: '#/definitions/handlers.UserAuthenticate.UserResponse'
        "401":
          description: User does not authorized
          schema:
            $ref: '#/definitions/middleware.CustomError'
        "410":
          description: Service does not responding (maybe crush)
          schema:
            $ref: '#/definitions/middleware.CustomError'
      summary: Authenticates user
      tags:
      - users
  /users/login:
    post:
      description: log in user with provided login and password
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users_pb.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully authorized
          schema:
            $ref: '#/definitions/handlers.UserLogin.UserResponse'
        "400":
          description: Invalid request data
          schema:
            $ref: '#/definitions/middleware.CustomError'
        "410":
          description: Service does not responding (maybe crush)
          schema:
            $ref: '#/definitions/middleware.CustomError'
      summary: Authorizes user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: Cookie
    name: Authorization
    type: apiKey
swagger: "2.0"
