name: lint-test

on:
  push:
    branches: ["main"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache: false

      - name: Dependencies set up
        run: make i

      - name: Lint
        run: make check

      - name: Test
        run: make test-unit
